localdb:
  image: postgres:11.2
  ports:
    - "5432:5432"
  volumes:
    - ./db/dumps:/app-db-dumps
  environment:
    - POSTGRES_USER=MaTMolina
    - POSTGRES_PASSWORD=taqtilew415
    - POSTGRES_DB=database-local

testdb:
  image: postgres:11.2
  ports:
    - "5433:5432"
  volumes:
    - ./db/dumps:/app-db-dumps
  environment:
    - POSTGRES_USER=MaTMolina
    - POSTGRES_PASSWORD=taqtilew415
    - POSTGRES_DB=database-test